language: php

php:
  - 5.3
  - 5.4

before_script:
- sh -c "composer global require 'phpunit/phpunit=3.7.33'"
- sh -c "mkdir ~/build/vinik/cryptpass1/vendor"
- sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ~/build/vinik/cryptpass1/vendor/PHPUnit"

script:
  - phpunit ~/build/vinik/cryptpass1/tests/CryptTest.php
